### PR TITLE
Persist for multiple refreshes

### PR DESCRIPTION
**Pull request by krevels**
I ran into a problem similar to #12 where the form state would only restore on the first refresh, but would disappear on subsequent ones.  

This appeared to occur because the `<Persist />` component would update after mount, containing the initial form values.  Additionally, `this.context.formik` is always null (I'm assuming b/c Formik no longer uses the legacy Context API), so it would cause whatever was in `prevProps` to always persist.  

Replacing `formik` from the context with the one passed via props seemed like the easiest approach here, but I feel that i might be missing something 🤔

### CODE REVIEW

**Comment by JulienWeiler** [comment]
Any news on this? Same issue here.

**Comment by nicodmf** [comment]
@jaredpalmer any news on this ?

**Comment by ishakimanuel** [comment]
this issue still appear on my app with formik persist version 1.1.0, any solution for this issue ?

**Comment by nicodmf** [comment]
@jaredpalmer it is very important PR, could you please review this.

**Comment by dunk** [comment]
@jaredpalmer Could do with having this merged, too.

**Review by jaredpalmer — APPROVED** [review]

**Comment by vytautasvargonas** [comment]
Can we have a version released with this commit?

**Comment by abohannon** [comment]
Did this fix the issue? I'm still unable to persist after the second refresh.

**Comment by ashik112** [comment]
> Did this fix the issue? I'm still unable to persist after the second refresh.

No, still not fixed in version 1.1.0. Can we please have another version released with the fixes? @jaredpalmer

**Comment by ishakimanuel** [comment]
i fix this issue by create a custom <Form> component that receive formik object, and run formik validateForm() function when component is mounted.

`  const validateForm = () => {
    if (formik && formik.validateForm && formik.setErrors) {
      formik.validateForm().then(() => {
        formik.setErrors({});
      });
    }
  };

  useEffect(() => {
    validateForm();

    return () => {};
  }, []);`

the setErrors function is optional if you want to run it or not

**Comment by collinc777** [comment]
@jaredpalmer just checking in here

**Comment by antoniojps** [comment]
👀 Same issue.

**Comment by PaulAndCode** [comment]
Same issue

**Comment by rudyportillo** [comment]
Same issue

**Comment by Carus11** [comment]
For those of you commenting that this issue persists in the published version, this library has only one code file (its very short and concise too), and the fix is in the master branch, you can grab that file and use it instead for the time being.

**Comment by ashik112** [comment]
Checking in after 1 year

**Comment by shamseerahammedm** [comment]
same issue here!

**Comment by kevinvugts** [comment]
@jaredpalmer re-opening this ticket since this one is still not release on the npm library. Would it be possible that you make a new build 1.1.2 on npm?  

Thanks in advance. 👍

**Pull request merged**
